# projConfig.toml for xlCluster_go

[meta]
    version = '0.1.0'

[project]
    name = 'xlCluster_go'  # distro name
    package = 'xlCluster_go'  # internal name
    proj_dir = '/home/jdd/dev/go/src/github.com/jddixon/xlCluster_go'
    main_lang = 'go'
    version = '1.9.12'
    version_date = '2017-10-22'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2014-2017'
    description = 'XLattice Cluster managed using xlReg_go'
    dev_status = 'alpha'
    license = 'mit'
    state = 'shared'
    url = 'https://jddixon.github.io/xlCluster_go'

[go]
    cmds=[]
